package generator.patterns;

public enum PatternGenerationType {
	SINGLE_PATTERN_1, SINGLE_PATTERN_2, SINGLE_PATTERN_3, 
	MULTIPLE_PATTERN_1, MULTIPLE_PATTERN_2, MULTIPLE_PATTERN_3,
	PATTERN_OCCURENCES, FORBIDDEN_PATTERN
}
