package generator.fragments;

public enum FragmentGenerationType {
	SINGLE_FRAGMENT_1, SINGLE_FRAGMENT_2, SINGLE_FRAGMENT_3, 
	MULTIPLE_FRAGMENT_1, MULTIPLE_FRAGMENT_2, MULTIPLE_FRAGMENT_3,
	FRAGMENT_OCCURENCES, FORBIDDEN_FRAGMENT
}
