package solving_modes;

public enum SolvingMode {
	RECTANGLE, CORONOID, CATACONDENSED, IRREGULARITY, SYMMETRIES, NB_CARBONS_HYDROGENS, 
	SINGLE_FRAGMENT_1, SINGLE_FRAGMENT_2, SINGLE_FRAGMENT_3,
	MULTIPLE_FRAGMENT_1, MULTIPLE_FRAGMENT_2, MULTIPLE_FRAGMENT_3, 
	FORBIDDEN_FRAGMENT, FRAGMENT_OCCURENCES
}
